### ISSUE TITLE
plant genome with raw HIFI reads

### ISSUE THREAD

**Issue by m-jahani** [marcelauliano/MitoHiFi#14]
Hi,

Thanks for the excellent tool.

I am trying to run mitohifi with raw reads of a plant genome using the following command:

mitohifi_v2.1.py -r Kalea.merged.ccs.contaminationfree.fasta -f MT361980.1.fasta -g MT361980.1.gb -t 40 -o 1  1>MITOHIFI1.LOG 2> MITOHIFI2.LOG

there were some genes from the reference genome not being recognized by mitofinder, so I modified mitohifi_v2.py code at lines 236 and 286 to include the --new-genes parameter at the mitofinder execution code. (base on https://github.com/marcelauliano/MitoHiFi/issues/11). However, motifhifi could not generate final_mitogenome.fasta and final_mitogenome.gb.

Attached are the log files and a list of files in the result directory.

Any idea what can cause the problem?

Thanks,
Mojtaba

[lift_files.txt](https://github.com/marcelauliano/MitoHiFi/files/7664431/lift_files.txt)
[MITOHIFI1.LOG](https://github.com/marcelauliano/MitoHiFi/files/7664432/MITOHIFI1.LOG)
[MITOHIFI2.LOG](https://github.com/marcelauliano/MitoHiFi/files/7664433/MITOHIFI2.LOG)
[ptg000009l.annotation_MitoFinder.log](https://github.com/marcelauliano/MitoHiFi/files/7664434/ptg000009l.annotation_MitoFinder.log)
[hifiasm.log](https://github.com/marcelauliano/MitoHiFi/files/7664435/hifiasm.log)
[ptg000009l_RC.annotation_MitoFinder.log](https://github.com/marcelauliano/MitoHiFi/files/7664436/ptg000009l_RC.annotation_MitoFinder.log)

**Comment by m-jahani** [comment]
Can you please answer my question? :)  Thanks

**Comment by marcelauliano** [comment]
Hi m-jahani! Can you have a look at the new release v2.2 ? Let me know what you can get with it =)
