### ISSUE TITLE
Bio.Alphabet removed from Biopython

### ISSUE THREAD

**Issue by sheinasim** [marcelauliano/MitoHiFi#2]
Hi there!

I cloned this recently and tried running with the current version of Biopython, and Bio.Alphabet is no longer available in the current version.

I changed the source code in a few spots using this as a guide https://biopython.org/wiki/Alphabet:

Commented out line 29 from circularizationCheck.modified.py
Removed ", generic_dna" from line 38 of circularizationCheck.modified.py
Commented out ", Alphabet" from line 10 of rotate.py

I didn't remove the instances of "Alphabet.generic_dna" in rotate.py and it seems to be okay.

These are just what i discovered for my version of Biopython. If these changes are made, not sure if it'll break for the older version.

Thanks!

**Comment by bgruening** [comment]
@sheinasim some fix is also included here: https://github.com/marcelauliano/MitoHiFi/pull/1 but I think mitofinder is still using python2, so this might be a problem.

**Comment by marcelauliano** [comment]
Sheina and Bjoern, thanks for the warnings! I'm aware of that. MitoHifi is going through a change: the idea will remain similar but the whole code will be python3 (no bash or older python) and you will also have the possibility to start from reads, map them to close-related species, assemble them and then parse.
New code to be available here in a few days!

**Comment by sheinasim** [comment]
@marcelauliano That sounds great! Will there also be an opportunity to identify the MT genome from a partial MT sequence?

**Comment by marcelauliano** [comment]
Hey Sheina, please try the new version on the branch v2 =) It should all be solved now!

git clone --branch mitohifi_v2 https://github.com/marcelauliano/MitoHiFi.git
