### ISSUE TITLE
Shebang on scripts copied to Docker image

### ISSUE THREAD

**Issue by brantfaircloth** [marcelauliano/MitoHiFi#22]
Hello,

First, thanks for your work on this program - it's very helpful!  When building the Docker image (for conversion to a singularity container), I ran into a couple of issues with the shebangs not being copied to the executable scripts correctly.  Specifically, it looked like the contents of `mitohifi.py` were being overwritten when the shebang is injected... which left a file/executable in the Docker image that contained only `/usr/bin/env python`.

I fixed the issue by manually pasting the correct shebang to the necessary files and commenting out the lines in the `Dockerfile` that inject these to the 3 scripts.  Then I rebuilt the image and all was well.

Thanks again for your work on this!

**Comment by ksenia-krasheninnikova** [comment]
Hello. You could pull an image directly from biocontainers: 

`docker pull biocontainers/mitohifi:2.2_cv1 `

Also, we've updated the Dockerfile on github in master branch. Perhaps the new version will work better for you.
For information, Docker version 19.03.13, build 4484c46d9d has been used for building the image locally.
