### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by bsierieb1** [marcelauliano/MitoHiFi#46]
`mitohifi.py` needs to be removed from the following line:
`singularity exec --bind /lustre/:/lustre/ docker://ghcr.io/marcelauliano/mitohifi:master mitohifi.py findMitoReference.py --species "Cryptosula pallasiana" --email your@email.for.ncbi.db.query --outfolder /data/ --min_length 16000`

**Comment by marcelauliano** [comment]
oh yes! thank you!
