### ISSUE TITLE
   reference_tRNA = max(tRNAs, key=tRNAs.get) ValueError: max() arg is an empty sequence , even though mito finder is working properly

### ISSUE THREAD

**Issue by mixle18** [marcelauliano/MitoHiFi#60]
Hi, 
I am trying to assemble the mitochondria of the plant genome. I am continuously getting the same error : 

Traceback (most recent call last):
  File "src/mitohifi.py", line 557, in <module>
    main()
  File "src/mitohifi.py", line 296, in main
    tRNA_ref = fetch.get_ref_tRNA()
  File "/media/safflower2/Data/megha/validation/mitochondria/MitoHiFi/src/fetch.py", line 48, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence

 Mitofinder and all the other dependencies working properly. I even tried it with mitos and it is giving the same error.
It would be very helpful if you suggest if you can suggest how can i resolve this issue.
 Also, please help if it is something related to the plant assembly.

**Comment by marcelauliano** [comment]
Hi, 
I'm almost sure this is related to the plant assembly. But before we explore this:
1-) Can you please paste here the exact command you ran.
2-) Can you please run the pipeline with the test dataset as described on Readme (item 4)

**Comment by marcelauliano** [comment]
Hi Manuela, if the conda installation it is difficult for me to debug. I advise the docker/singularity version. However, if it says it has 'no annotation file' it is something with MitoFinder. You need to be sure it is working properly and it's been rightly called according to your installation set up. Is MitoFinder installed and exported to the PATH? Let me know how it goes!

**Comment by mkrueger80** [comment]
Hi,
Mitofinder is in the PATH. 
I also installed everything manually, but the same error persists.
I am going to test if Mitofinder is working properly and when this does not solve the problem I am going to try the docker/singularity version.
I will let you know if this solved the problem or not.
Cheers,
Manuela.

**Comment by mixle18** [comment]
Hi, 
Thank you for getting back to me. It was the problem of the mitofinder configuration only. It resolved once i configured Mitofinder again. I successfully raN mitochondrial assembly for my genome. cheers!


I am trying to use mitohifi for the chloroplast assembly.  My command is
 python /media/lab7ibm/f69b46e6-07ce-4d36-9b7b-7e88dca9f5d4/Praveen/Tools/MitoHiFi/src/mitohifi.py  -c primary_assembly_contig_level_SaF.bp.p_ctg.fa -f saf_ref.fasta -g saf_ref.gb -t 30 -a plant

However, in the documentation you mentioned "Also, the script findMitoReference.py can now search for a chloroplast instead of mitochondria. Use flag -t chloroplast", but -t  is also used for threads flag. I am a bit confused, can you help?


Thanks 
Megha

**Comment by marcelauliano** [comment]
Hi Megha, the script findMitoReference.py uses -t for setting what to search for, it is not threaded. 

So you do: python findMitoReference.py --type chloroplast --species "your species name"

then you run as you mentioned before:

mitohifi.py -c primary_assembly_contig_level_SaF.bp.p_ctg.fa -f "your species ref.fa"-g "your species ref.gb" -t 30 -a plant

**Comment by mkrueger80** [comment]
Hi,
I just wanted to let you know, that the error I reported was definitely caused by mitofinder, as it has problems with some of the genbank files to recognize the genes (e.g., accessions for S.latifolia (mitochondrion) HM562727 and S. vulgaris (MH455602-06).
This is solved within mitofinder with using --new-genes (for S.latifolia) for S. vulgaris I had to slightly change the gb file.
Cheers,
Manuela.

**Comment by zhyx6511** [comment]
Hi mixle18


> Hi, Thank you for getting back to me. It was the problem of the mitofinder configuration only. It resolved once i configured Mitofinder again. I successfully raN mitochondrial assembly for my genome. cheers!
> 
> I am trying to use mitohifi for the chloroplast assembly. My command is python /media/lab7ibm/f69b46e6-07ce-4d36-9b7b-7e88dca9f5d4/Praveen/Tools/MitoHiFi/src/mitohifi.py -c primary_assembly_contig_level_SaF.bp.p_ctg.fa -f saf_ref.fasta -g saf_ref.gb -t 30 -a plant
> 
> However, in the documentation you mentioned "Also, the script findMitoReference.py can now search for a chloroplast instead of mitochondria. Use flag -t chloroplast", but -t is also used for threads flag. I am a bit confused, can you help?
> 
> Thanks Megha

Can you tell me how to configure mitofinder  you ? I install it by conda, but mitfi folder is missing，And according to the installation method on the official website，I can't get it to install successfully on ubuntu 22.04 system，Looking forward to your reply，thank you very much.
