### ISSUE TITLE
problem installing MitoHiFi

### ISSUE THREAD

**Issue by Brent-Saylor-Canopy** [marcelauliano/MitoHiFi#7]
Hi when I try and install MitoHiFi using the following code from your readme.

```
git clone --branch mitohifi_v2 https://github.com/marcelauliano/MitoHiFi.git
```
I get the following error
```
Cloning into 'MitoHiFi'...
fatal: Remote branch mitohifi_v2 not found in upstream origin
```

**Comment by marcelauliano** [comment]
Dear Brent, 
Please just do ``` git clone https://github.com/marcelauliano/MitoHiFi.git ```
and you will have the latest version of  MitoHifi.
Best,
Marcela.
