### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by zhyx6511** [marcelauliano/MitoHiFi#70]
dear Marcela and your team，I am running the mitohifi pipeline with an error as shown in the screenshot below, I have searched a lot about the cause and solution of this error but with no luck at all, and had to ask you for advice as well. I look forward to your reply, and I will be endlessly grateful.Thank you very much.
Traceback (most recent call last):
File "/mnt/biosoft_1/MitoHiFi-master/src/mitohifi.py", line 557, in <module>
    main()
File "/mnt/biosoft_1/MitoHiFi-master/src/mitohifi.py", line 296, in main
    tRNA_ref = fetch.get_ref_tRNA()
File "/mnt/biosoft_1/MitoHiFi-master/src/fetch.py", line 48, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence

**Comment by marcelauliano** [comment]
Hi, if you are running a local installation, you will need to make sure everything is installed correctly. It seems to me like an annotation error. Make sure mitofinder or mitos are installed correctly. Apart from that, we advise people to use the docker container version with docker or singularity
