### ISSUE TITLE
ModuleNotFoundError: No module named 'parse_blast'

### ISSUE THREAD

**Issue by AlcaArctica** [marcelauliano/MitoHiFi#74]
Hi, I installed the mitohifi conda env (with `mamba env create -n mitohifi2 -f mitohifi_env.yml`) but I still get some import error

```
conda activate mitohifi2
python mitohifi.py -r ilDeiPorc1.reads.100.fa -f OQ694980.1.fasta -g OQ694980.1.gb -t 4 -o 5
Traceback (most recent call last):
  File "mitohifi.py", line 14, in <module>
    import parse_blast
ModuleNotFoundError: No module named 'parse_blast'
```

What do I need to install to solve this error?

**Comment by marcelauliano** [comment]
Hi sorry, we don't have the capacity to help with problems outside of of the docker container. But it seems to me you are not executing the script where the modules are?
Good luck

**Comment by AlcaArctica** [comment]
Yes, that was indeed the problem. I should not have moved the script. Sorry for the hassle.
