### ISSUE TITLE
hifiasm assembly is creating a larger than expected contig

### ISSUE THREAD

**Issue by Labarcena-Jessica** [marcelauliano/MitoHiFi#82]
There is a problem with implementing hifiasm in this pipeline. I am working with a mitogenome less than 18K bp, and the contig generated by hifiasm is 50K. I run Hifiasm independently, and the same error happens, so it seems to be a problem with the assembler.  Just to be sure that the problem wasn't on my data I run IPA and the assembly generated had the expected length. Any ideas of what might be happening?

**Comment by marcelauliano** [comment]
Hi Jessica, 

This is exactly what de novo assemblers do while assembling circular molecules. This is why MitoHiFi was developed: among other things, to remove redundancy of contigs.
I hope the pipeline has worked for you. :)
Best,
Marcela.

**Comment by Labarcena-Jessica** [comment]
Hi Marcela, 

Thank you for your quick response. i am sorry if I wasn't clear. MitoHifi is giving me the larger than expected contig. 
![final_mitogenome annotation](https://github.com/marcelauliano/MitoHiFi/assets/57112441/b9fb5d36-3076-4f0f-8655-7d394d1b4792)
Please see the figure attached. 

Thanks for your help

With warm regards,

Jessica

**Comment by Labarcena-Jessica** [comment]
![final_mitogenome annotation](https://github.com/marcelauliano/MitoHiFi/assets/57112441/656c7012-8e93-4436-9ae5-833580c8e817)
This is after running with the contigs.
