### ISSUE TITLE
mitohifi error

### ISSUE THREAD

**Issue by gauravcodepro** [marcelauliano/MitoHiFi#97]
Hi i am getting this error while running the latest version of the Mitohifi, i read the previous ones but they seems to be not-working. 
```
  File "mitohifi.py", line 302, in main
    tRNA_ref = fetch.get_ref_tRNA()
  File "/work/sablok/organelle/mitochondrial/MitoHiFi-master/src/fetch.py", line 48, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence
```
can you help with the same. 
Thank you,
Gaurav

**Comment by zajacn** [comment]
I am getting the same issue. Following the previous issues reported I ran the mitohifi through conda installation but then also through singularity. 

For singularity I ran:
singularity build mitohifi.sif docker://ghcr.io/marcelauliano/mitohifi:master 
singularity exec -B $PWD mitohifi.sif mitohifi.py -c contigs.fasta -f reference.fasta -g reference.gbk -t 1 -a animal --circular-size 14000 

Error I get:
Traceback (most recent call last):
  File "/opt/MitoHiFi/src/mitohifi.py", line 566, in <module>
    main()
  File "/opt/MitoHiFi/src/mitohifi.py", line 303, in main
    tRNA_ref = fetch.get_ref_tRNA()
  File "/opt/MitoHiFi/src/fetch.py", line 48, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence

**Comment by gauravcodepro** [comment]
Hi any possible solution or alternative for the same. Did you @zajacn figured out another version. Thank you for the information.
